export const MESSAGE = {
  TOAST_INTERVAL : 10000,
  NON_EMPTY: "This field is required",
    PASSWORD_POLICY_UPDATE: 'Password policy updated successfully',
    ROLE_CREATED: 'Role created successfully',
    ROLE_UPDATED: 'Role updated successfully',
    ROLE_DELETED: 'Role Deleted successfully',
    PAYMENT_INSTRUMENT_SUCCESS: 'Payment instruments updated successfully',
    USER_CREATED: 'User created successfully',
    USER_PROFILE_UPDATED: 'User profile updated successfully',
    USER_UPDATED: 'User updated successfully',
    USER_DELETED: 'User deleted successfully',
    PASSWORD_RESET: 'Password Reset successfully',
    OPPS_ERROR: 'Oops something went wrong.',
    WRONG_LOGIN_PASSWORD : 'Please enter a correct Login Password',
    LIMIT_PROFILE_DELETE: 'Limit profile deleted successfully',
    LIMIT_PROFILE_UPDATED: 'Limit profile updated successfully.',
    LIMIT_PROFILE_CREATED: 'Limit profile created successfully',
    LIMIT_PROFILE_APPROVED: 'Limit profile approved successfully',
    FULFILMENT_OPTION: 'Fulfilment option updated successfully',
    PASSWORD_CHANGE_SUCCSS: 'Password changed successfully.',
    PASSWORD_ERROR: 'Please fill correct values for new password and confirm password.',
    APPROVED_MERCHANT: 'Merchant Approved successfully',
    VALUE_VALIDATION: 'Please fill out valid information.',
    SENT_FOR_APPROVAL: 'Record sent for approval',
    SAVED_SUCCESS: "Saved successfully",
    OWNER_EXCEED: "You have exceeded 5 attends for add Owner",
    PHONE_NUMBER: "This field must contain a valid Phone number",
    ZIP_CODE: "This field must contain a valid zip code",
    EMAIL_ADDRESS: "This field must contain a valid email ",
    GREATER_THAN_1: "This field requires value greater than 1",
    RANGE2_9: "Value should vary between 2 to 9",
    REMAINDER_DAYS: "Password change reminder days should be less than password expiry days",
    MINIMUM_LENGTH: "Maximum Length and Minimum characters length not matching",
    MINIMUM_LENGTH_VARY: "Minimum Length should be less than Maximum Length",
    BOTH_PASSWORDS: "Both password do not match",
    ORDERITEMS: "You have exceeded 5 attends for adding Order Items",
    TRANSACTION_COMPLETED: "Transaction completed successfully",
    ERROR_AMOUNT_ORDER_MISMATCH: "Amount should match with orders total",
    CARD_DELETE: "Card Deleted Successfully ",
    BUYER_UPDATED: "Buyer updated successfully",
    BUYER_CREATED: "Buyer created successfully",
    CUSTOMER_DELETED: 'Customer deleted successfully',
    FORGOT_PASSWORD: 'An email containing a link to reset password will be sent if this username/email has a registered account',
    ITEMSEXCEED: "You have exceeded 10 attends for adding Items",
    INVOICE_CREATE: "Invoice created successfully",
    INVOICE_MODIFY: "Invoice updated successfully",
    INVOICE_DELETE: "Invoice deleted successfully",
    INVOICE_MARK_PAID: "Invoice marked as Paid successfully",
    BANK_ACCOUNT_DELETE: "Bank account deleted successfully ",
    INVOICE_CANCEL:"Invoice cancelled successfully",
    CARD_NOT_VALID : "Card number or expiry date not valid",
    CUSTOMER_INVALID_DETAILS : "You are entering invalid customer details",
    RECURRING_PAYMENT_UPDATED : "Recurring payment updated successfully",
    RECURRING_PAYMENT_CREATED : "Recurring payment created successfully",
    PRODUCT_CREATED: 'Product created successfully',
    PRODUCT_UPDATED: 'Product updated successfully',
    PRODUCT_DELETED: 'Product Deleted successfully',
    INVOICE_UPDATED: "Invoice updated successfully"
  
}